path:
  ckpt_path: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/logtrain/multilingual_test_2"
  log_path: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/logtrain/multilingual_test_2"
  result_path: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/logtrain/multilingual_test_2"
optimizer:
  batch_size: 4
  batch_size_eval: 4
  num_sample: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [200000, 300000, 400000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 1000
  synth_step: 1000
  val_step: 1000
  save_step: 10000
