path:
  ckpt_path: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/logtrain/Multilingual_Style_LS_6L_balance_Language_V1/Original_Norm_EVD_DF_LS"
  log_path: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/logtrain/Multilingual_Style_LS_6L_balance_Language_V1/Original_Norm_EVD_DF_LS"
  result_path: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/logtrain/Multilingual_Style_LS_6L_balance_Language_V1/Original_Norm_EVD_DF_LS"
checkpoint:
  pretrained: "/home/s2220411/Code/Log_data/training/Multilingual_V2/480000.pth.tar"
  path_hifigan: "/home/ldap-users/s2220411/Code/FastSpeech2_multilingual"
optimizer:
  batch_size: 30
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.5
  init_lr: 0.001
step:
  total_step_aux: 160000
  total_step_naive: 160000
  total_step_shallow: 320000
  total_step: 900000
  log_step: 1000  #100
  synth_step: 1000 #1000
  val_step: 1000 #1000
  save_step: 10000 #10000
loss:
  noise_loss: "l1"
  dur_loss: "mse"
  pitch_loss: "l1"
  cwt_loss: "l1"
  # cwt_add_f0_loss: false
  lambda_f0: 1.0
  lambda_uv: 1.0
  lambda_ph_dur: 1.0
  lambda_word_dur: 1.0
  lambda_sent_dur: 1.0

