path:
  ckpt_path: "/root/Code/Log_Training/FastSpeech2/logtrain/multilingual_test_3"
  log_path: "/root/Code/Log_Training/FastSpeech2/logtrain/multilingual_test_3"
  result_path: "/root/Code/Log_Training/FastSpeech2/logtrain/multilingual_test_3"
checkpoint:
  pretrained: "/home/ldap-users/s2220411/Code/Log_Training/FastSpeech2/pretrained/900000.pth.tar"
  path_hifigan: "/home/ldap-users/s2220411/Code/FastSpeech2_multilingual"
optimizer:
  batch_size: 1
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 1000  #100
  synth_step: 1000 #1000
  val_step: 1000 #1000
  save_step: 10000 #100000
