dataset: "LibriTTS"

path:
  corpus_path: "/project/AI-team/exp/chungtran/tts/StyleSpeech/dataset/wav22050_multilingual"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/project/AI-team/exp/chungtran/tts/StyleSpeech/dataset/wav22050_multilingual"
  preprocessed_path: "/data/processed/speech/tts/Adaptation_Multilingual_folder/Adaptation_Multilingual_Diffsinger"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["multi_language_cleaners"]
    language: "mul"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    pitch_type: "cwt" # support 'frame', 'ph', 'cwt'
    pitch_norm: "log" # support 'standard', 'log'
    pitch_norm_eps: 0.000000001
    pitch_ar: False
    with_f0: True
    with_f0cwt: True
    use_uv: True
    f0_mean: 214.31683793057
    f0_std: 63.97520977575229
    cwt_scales: -1
  energy:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
